Update hub-mirror.yml

diff --git a/.github/workflows/hub-mirror.yml b/.github/workflows/hub-mirror.yml
--- a/.github/workflows/hub-mirror.yml
+++ b/.github/workflows/hub-mirror.yml
@@ -24,6 +24,13 @@ jobs:
         uses: actions/setup-go@v4
         with:
           go-version: '1.20'
+      # 2.半.测试网络通不通
+      - name: Test network
+        run: |
+          nslookup ghcr.io
+          nslookup index.docker.io
+          curl -I https://ghcr.io/v2/
+          docker pull hello-world || echo "pull failed"
       # 3. 运行 go 代码
       - name: Run code
         run: go run main.go --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_TOKEN }} --repository=${{ secrets.DOCKER_REPOSITORY }} --content='${{ github.event.issue.body }}' --maxContent=11 --outputPath=output.md
